import { Route } from "@/src/infra/shared/entities/Route";
import { JsonValue } from "@/src/models/map/Maps/Map";
import { buildMindMapPrompt } from "@/src/models/map/Maps/fns/buildMindMapPrompt";
import { deepenAllLeafNodes } from "@/src/models/map/Maps/fns/deepenAllLeafNodes";
import { normalizeMindMapNodesFromAi } from "@/src/models/map/Maps/fns/normalizeMindMapNodesFromAi";
import {
  createMapFromAiBody,
  createMapFromAiResponses,
} from "./createMapFromAi.gateway";

const DEFAULT_TITLE = "Mapa gerado";

function deriveTitle(description: string, optionalTitle?: string): string {
  const trimmed = optionalTitle?.trim();
  if (trimmed && trimmed.length > 0) {
    return trimmed.slice(0, 256);
  }
  const fromDesc = description.trim().slice(0, 256);
  return fromDesc || DEFAULT_TITLE;
}

export const createMapFromAiRoute = Route.create({
  path: "/v1/maps/from-ai",
  method: "post",
  tags: ["Maps"],
  summary: "Create map from AI",
  description:
    "Create a map with content generated by AI from the user's description.",
  body: createMapFromAiBody,
  response: createMapFromAiResponses,
  preHandler: [Route.canRequest("read:organization")],
  handler: async (request, reply, { modules }) => {
    const { Maps } = modules.map;
    const { OpenAi } = modules.openai;
    const member = request.context.member;

    const description = request.body.description;
    const title = deriveTitle(description, request.body.title);

    const prompt = buildMindMapPrompt(description);

    const result = await OpenAi.generateJson({
      client: modules.openai.client,
      prompt,
    });

    const normalizedNodes = normalizeMindMapNodesFromAi(result.data);
    let content = normalizedNodes as JsonValue[];

    content = await deepenAllLeafNodes(content, {
      generateJson: OpenAi.generateJson,
      client: modules.openai.client,
    });

    const { map } = await Maps.create({
      member_id: member.id,
      title,
      content,
      generated_by_ai: true,
    });

    return reply.status(201).send({
      status: 201,
      data: { map_id: map.id },
    });
  },
});
